# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesApp
  pod 'HexColors'
  pod 'CellRegistrable', :git => 'https://github.com/KogiMobileSAS/CellRegistrable.git', :branch => 'swift3'
  pod 'Alamofire'
  pod 'Wrap', '~> 2.0'
  pod 'Unbox', '~> 2.2.0'
  pod 'RealmSwift'
  pod 'AlamofireImage', '~> 3.1'
 
  #RxSwift
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxBlocking', '~> 3.0'
  pod 'RxRealm'
 
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
